import type { QuestArchetype } from '../models/questTypes.js';

export const QUEST_NAME_PARTS: Record<QuestArchetype, { prefixes: string[]; suffixes: string[] }> = {
	battler: {
		prefixes: [
			'Iron',
			'Crimson',
			'Shadow',
			'Bloodforged',
			'Stormborn',
			'Obsidian',
			'Vengeful',
			'Savage',
			'Blazing',
			'Warbound',
			'Ashen',
			'Steelclad',
			'Thunderous',
			'Relentless',
			'Grim',
			'Cursed',
			'Wrathful',
			'Broken',
			'Infernal',
			'Frostbound',
		],
		suffixes: [
			'Arena',
			'Conquest',
			'Trial',
			'Reckoning',
			'Uprising',
			'Crusade',
			'Gauntlet',
			'Siege',
			'Dominion',
			'Clash',
			'Retribution',
			'Onslaught',
			'Bloodshed',
			'Warpath',
			'Rampage',
			'Skirmish',
			'Cataclysm',
			'Battlefront',
			'Ascension',
			'Decimation',
		],
	},
	traveller: {
		prefixes: [
			'Whispering',
			'Golden',
			'Forgotten',
			'Wandering',
			'Silver',
			'Distant',
			'Hidden',
			'Emerald',
			'Shattered',
			'Eternal',
			'Fading',
			'Moonlit',
			'Sunken',
			'Silent',
			'Lost',
			'Sacred',
			'Starlit',
			'Roaming',
			'Boundless',
			'Veiled',
		],
		suffixes: [
			'Horizon',
			'Path',
			'Voyage',
			'Frontier',
			'Passage',
			'Odyssey',
			'Trail',
			'Crossing',
			'Expanse',
			'Journey',
			'Way',
			'Expedition',
			'Pilgrimage',
			'Ascent',
			'Descent',
			'Drift',
			'Passageway',
			'Summit',
			'Reach',
			'Awakening',
		],
	},
};

