// --- Monster definitions ---
export const MONSTER_DEFS = [
	// Plains/Forest
	{
		id: 'weak_trollkin',
		name: 'Weak Trollkin',
		biome: 'plains,forest',
		health: 2,
		attack: 1,
		attackChance: 0.5,
		defense: 1,
		defenseChance: 0.33,
		img: 'trollkin.png',
	},
	{
		id: 'trollkin',
		name: 'Trollkin',
		biome: 'plains,forest',
		health: 2,
		attack: 2,
		attackChance: 0.7,
		defense: 2,
		defenseChance: 0.5,
		img: 'trollkin.png',
	},
	{
		id: 'strong_trollkin',
		name: 'Strong Trollkin',
		biome: 'plains,forest',
		health: 2,
		attack: 3,
		attackChance: 0.9,
		defense: 3,
		defenseChance: 0.7,
		img: 'trollkin.png',
	},
	{
		id: 'weak_bat',
		name: 'Weak Bat',
		biome: 'plains,forest',
		health: 2,
		attack: 1,
		attackChance: 0.7,
		defense: 1,
		defenseChance: 0.33,
		img: 'bat.png',
	},
	{
		id: 'bat',
		name: 'Bat',
		biome: 'plains,forest',
		health: 2,
		attack: 2,
		attackChance: 0.7,
		defense: 2,
		defenseChance: 0.5,
		img: 'bat.png',
	},
	{
		id: 'strong_bat',
		name: 'Strong Bat',
		biome: 'plains,forest',
		health: 2,
		attack: 3,
		attackChance: 0.9,
		defense: 3,
		defenseChance: 0.7,
		img: 'bat.png',
	},
	{
		id: 'weak_fairy',
		name: 'Weak Fairy',
		biome: 'plains,forest',
		health: 2,
		attack: 1,
		attackChance: 0.5,
		defense: 1,
		defenseChance: 0.33,
		img: 'fairy.png',
	},
	{
		id: 'fairy',
		name: 'Fairy',
		biome: 'plains,forest',
		health: 2,
		attack: 2,
		attackChance: 0.7,
		defense: 2,
		defenseChance: 0.5,
		img: 'fairy.png',
	},
	{
		id: 'strong_fairy',
		name: 'Strong Fairy',
		biome: 'plains,forest',
		health: 2,
		attack: 3,
		attackChance: 0.9,
		defense: 3,
		defenseChance: 0.7,
		img: 'fairy.png',
	},
	{
		id: 'weak_black_cat',
		name: 'Weak Black Cat',
		biome: 'plains,forest',
		health: 2,
		attack: 1,
		attackChance: 0.5,
		defense: 1,
		defenseChance: 0.33,
		img: 'black_cat.png',
	},
	{
		id: 'black_cat',
		name: 'Black Cat',
		biome: 'plains,forest',
		health: 2,
		attack: 2,
		attackChance: 0.7,
		defense: 2,
		defenseChance: 0.5,
		img: 'black_cat.png',
	},
	{
		id: 'strong_black_cat',
		name: 'Strong Black Cat',
		biome: 'plains,forest',
		health: 2,
		attack: 3,
		attackChance: 0.9,
		defense: 3,
		defenseChance: 0.7,
		img: 'black_cat.png',
	},
	{
		id: 'weak_goblin',
		name: 'Weak Goblin',
		biome: 'plains,forest',
		health: 2,
		attack: 1,
		attackChance: 0.5,
		defense: 1,
		defenseChance: 0.33,
		img: 'goblin.png',
	},
	{
		id: 'goblin',
		name: 'Goblin',
		biome: 'plains,forest',
		health: 2,
		attack: 2,
		attackChance: 0.7,
		defense: 2,
		defenseChance: 0.5,
		img: 'goblin.png',
	},
	{
		id: 'strong_goblin',
		name: 'Strong Goblin',
		biome: 'plains,forest',
		health: 2,
		attack: 3,
		attackChance: 0.9,
		defense: 3,
		defenseChance: 0.7,
		img: 'goblin.png',
	},
	{
		id: 'weak_bigfoot',
		name: 'Weak Bigfoot',
		biome: 'plains,forest',
		health: 2,
		attack: 1,
		attackChance: 0.7,
		defense: 1,
		defenseChance: 0.33,
		img: 'bigfoot.png',
	},
	{
		id: 'bigfoot',
		name: 'Bigfoot',
		biome: 'plains,forest',
		health: 2,
		attack: 2,
		attackChance: 0.7,
		defense: 2,
		defenseChance: 0.5,
		img: 'bigfoot.png',
	},
	{
		id: 'strong_bigfoot',
		name: 'Strong Bigfoot',
		biome: 'plains,forest',
		health: 2,
		attack: 3,
		attackChance: 0.9,
		defense: 3,
		defenseChance: 0.7,
		img: 'bigfoot.png',
	},
	{
		id: 'weak_giant_spider',
		name: 'Weak Giant Spider',
		biome: 'plains,forest',
		health: 2,
		attack: 1,
		attackChance: 0.5,
		defense: 1,
		defenseChance: 0.33,
		img: 'giant_spider.png',
	},
	{
		id: 'giant_spider',
		name: 'Giant Spider',
		biome: 'plains,forest',
		health: 2,
		attack: 2,
		attackChance: 0.7,
		defense: 2,
		defenseChance: 0.5,
		img: 'giant_spider.png',
	},
	{
		id: 'strong_giant_spider',
		name: 'Strong Giant Spider',
		biome: 'plains,forest',
		health: 2,
		attack: 3,
		attackChance: 0.9,
		defense: 3,
		defenseChance: 0.7,
		img: 'giant_spider.png',
	},
	{
		id: 'weak_ogre',
		name: 'Weak Ogre',
		biome: 'plains,forest',
		health: 2,
		attack: 1,
		attackChance: 0.7,
		defense: 1,
		defenseChance: 0.33,
		img: 'ogre.png',
	},
	{
		id: 'ogre',
		name: 'Ogre',
		biome: 'plains,forest',
		health: 2,
		attack: 2,
		attackChance: 0.7,
		defense: 2,
		defenseChance: 0.5,
		img: 'ogre.png',
	},
	{
		id: 'strong_ogre',
		name: 'Strong Ogre',
		biome: 'plains,forest',
		health: 2,
		attack: 3,
		attackChance: 0.9,
		defense: 3,
		defenseChance: 0.7,
		img: 'ogre.png',
	},
	{
		id: 'weak_warewolf',
		name: 'Weak Warewolf',
		biome: 'plains,forest',
		health: 2,
		attack: 1,
		attackChance: 0.5,
		defense: 1,
		defenseChance: 0.33,
		img: 'warewolf.png',
	},
	{
		id: 'warewolf',
		name: 'Warewolf',
		biome: 'plains,forest',
		health: 2,
		attack: 2,
		attackChance: 0.7,
		defense: 2,
		defenseChance: 0.5,
		img: 'warewolf.png',
	},
	{
		id: 'strong_warewolf',
		name: 'Strong Warewolf',
		biome: 'plains,forest',
		health: 2,
		attack: 3,
		attackChance: 0.9,
		defense: 3,
		defenseChance: 0.7,
		img: 'warewolf.png',
	},
	// Desert
	{
		id: 'weak_spiky_lizard',
		name: 'Weak Spiky Lizard',
		biome: 'desert',
		health: 2,
		attack: 1,
		attackChance: 0.5,
		defense: 1,
		defenseChance: 0.33,
		img: 'spiky_lizard.png',
	},
	{
		id: 'spiky_lizard',
		name: 'Spiky Lizard',
		biome: 'desert',
		health: 2,
		attack: 2,
		attackChance: 0.7,
		defense: 2,
		defenseChance: 0.5,
		img: 'spiky_lizard.png',
	},
	{
		id: 'strong_spiky_lizard',
		name: 'Strong Spiky Lizard',
		biome: 'desert',
		health: 2,
		attack: 3,
		attackChance: 0.9,
		defense: 3,
		defenseChance: 0.7,
		img: 'spiky_lizard.png',
	},
	{
		id: 'weak_scorpion',
		name: 'Weak Scorpion',
		biome: 'desert',
		health: 2,
		attack: 1,
		attackChance: 0.5,
		defense: 1,
		defenseChance: 0.33,
		img: 'scorpion.png',
	},
	{
		id: 'scorpion',
		name: 'Scorpion',
		biome: 'desert',
		health: 2,
		attack: 2,
		attackChance: 0.7,
		defense: 2,
		defenseChance: 0.5,
		img: 'scorpion.png',
	},
	{
		id: 'strong_scorpion',
		name: 'Strong Scorpion',
		biome: 'desert',
		health: 2,
		attack: 3,
		attackChance: 0.9,
		defense: 3,
		defenseChance: 0.7,
		img: 'scorpion.png',
	},
	{
		id: 'weak_snake',
		name: 'Weak Snake',
		biome: 'desert',
		health: 2,
		attack: 1,
		attackChance: 0.5,
		defense: 1,
		defenseChance: 0.33,
		img: 'snake.png',
	},
	{
		id: 'snake',
		name: 'Snake',
		biome: 'desert',
		health: 2,
		attack: 2,
		attackChance: 0.7,
		defense: 2,
		defenseChance: 0.5,
		img: 'snake.png',
	},
	{
		id: 'strong_snake',
		name: 'Strong Snake',
		biome: 'desert',
		health: 2,
		attack: 3,
		attackChance: 0.9,
		defense: 3,
		defenseChance: 0.7,
		img: 'snake.png',
	},
	{
		id: 'weak_vulture',
		name: 'Weak Vulture',
		biome: 'desert',
		health: 2,
		attack: 1,
		attackChance: 0.5,
		defense: 1,
		defenseChance: 0.33,
		img: 'vulture.png',
	},
	{
		id: 'vulture',
		name: 'Vulture',
		biome: 'desert',
		health: 2,
		attack: 2,
		attackChance: 0.7,
		defense: 2,
		defenseChance: 0.5,
		img: 'vulture.png',
	},
	{
		id: 'strong_vulture',
		name: 'Strong Vulture',
		biome: 'desert',
		health: 2,
		attack: 3,
		attackChance: 0.9,
		defense: 3,
		defenseChance: 0.7,
		img: 'vulture.png',
	},
	{
		id: 'weak_harpy',
		name: 'Weak Harpy',
		biome: 'desert',
		health: 2,
		attack: 1,
		attackChance: 0.5,
		defense: 1,
		defenseChance: 0.33,
		img: 'harpy.png',
	},
	{
		id: 'harpy',
		name: 'Harpy',
		biome: 'desert',
		health: 2,
		attack: 2,
		attackChance: 0.7,
		defense: 2,
		defenseChance: 0.5,
		img: 'harpy.png',
	},
	{
		id: 'strong_harpy',
		name: 'Strong Harpy',
		biome: 'desert',
		health: 2,
		attack: 3,
		attackChance: 0.9,
		defense: 3,
		defenseChance: 0.7,
		img: 'harpy.png',
	},
	{
		id: 'weak_centaur',
		name: 'Weak Centaur',
		biome: 'desert',
		health: 2,
		attack: 1,
		attackChance: 0.5,
		defense: 1,
		defenseChance: 0.33,
		img: 'centaur.png',
	},
	{
		id: 'centaur',
		name: 'Centaur',
		biome: 'desert',
		health: 2,
		attack: 2,
		attackChance: 0.7,
		defense: 2,
		defenseChance: 0.5,
		img: 'centaur.png',
	},
	{
		id: 'strong_centaur',
		name: 'Strong Centaur',
		biome: 'desert',
		health: 2,
		attack: 3,
		attackChance: 0.9,
		defense: 3,
		defenseChance: 0.7,
		img: 'centaur.png',
	},
	{
		id: 'weak_sand_golem',
		name: 'Weak Sand Golem',
		biome: 'desert',
		health: 2,
		attack: 1,
		attackChance: 0.5,
		defense: 1,
		defenseChance: 0.33,
		img: 'sand_golem.png',
	},
	{
		id: 'sand_golem',
		name: 'Sand Golem',
		biome: 'desert',
		health: 2,
		attack: 2,
		attackChance: 0.7,
		defense: 2,
		defenseChance: 0.5,
		img: 'sand_golem.png',
	},
	{
		id: 'strong_sand_golem',
		name: 'Strong Sand Golem',
		biome: 'desert',
		health: 2,
		attack: 3,
		attackChance: 0.9,
		defense: 3,
		defenseChance: 0.7,
		img: 'sand_golem.png',
	},
	{
		id: 'weak_pheonix',
		name: 'Weak Pheonix',
		biome: 'desert',
		health: 2,
		attack: 1,
		attackChance: 0.5,
		defense: 1,
		defenseChance: 0.33,
		img: 'pheonix.png',
	},
	{
		id: 'pheonix',
		name: 'Pheonix',
		biome: 'desert',
		health: 2,
		attack: 2,
		attackChance: 0.7,
		defense: 2,
		defenseChance: 0.5,
		img: 'pheonix.png',
	},
	{
		id: 'strong_pheonix',
		name: 'Strong Pheonix',
		biome: 'desert',
		health: 2,
		attack: 3,
		attackChance: 0.9,
		defense: 3,
		defenseChance: 0.7,
		img: 'pheonix.png',
	},
	{
		id: 'weak_gryphon',
		name: 'Weak Gryphon',
		biome: 'desert',
		health: 2,
		attack: 1,
		attackChance: 0.5,
		defense: 1,
		defenseChance: 0.33,
		img: 'gryphon.png',
	},
	{
		id: 'gryphon',
		name: 'Gryphon',
		biome: 'desert',
		health: 2,
		attack: 2,
		attackChance: 0.7,
		defense: 2,
		defenseChance: 0.5,
		img: 'gryphon.png',
	},
	{
		id: 'strong_gryphon',
		name: 'Strong Gryphon',
		biome: 'desert',
		health: 2,
		attack: 3,
		attackChance: 0.9,
		defense: 3,
		defenseChance: 0.7,
		img: 'gryphon.png',
	},
	// Cave/Volcano
	{
		id: 'weak_fire_butterfly',
		name: 'Weak Fire Butterfly',
		biome: 'volcano,cave',
		health: 2,
		attack: 1,
		attackChance: 0.5,
		defense: 1,
		defenseChance: 0.33,
		img: 'fire_butterfly.png',
	},
	{
		id: 'fire_butterfly',
		name: 'Fire Butterfly',
		biome: 'volcano,cave',
		health: 2,
		attack: 2,
		attackChance: 0.7,
		defense: 2,
		defenseChance: 0.5,
		img: 'fire_butterfly.png',
	},
	{
		id: 'strong_fire_butterfly',
		name: 'Strong Fire Butterfly',
		biome: 'volcano,cave',
		health: 2,
		attack: 3,
		attackChance: 0.9,
		defense: 3,
		defenseChance: 0.7,
		img: 'fire_butterfly.png',
	},
	{
		id: 'weak_magma_cube',
		name: 'Weak Magma Cube',
		biome: 'volcano,cave',
		health: 2,
		attack: 1,
		attackChance: 0.5,
		defense: 1,
		defenseChance: 0.33,
		img: 'magma_cube.png',
	},
	{
		id: 'magma_cube',
		name: 'Magma Cube',
		biome: 'volcano,cave',
		health: 2,
		attack: 2,
		attackChance: 0.7,
		defense: 2,
		defenseChance: 0.5,
		img: 'magma_cube.png',
	},
	{
		id: 'strong_magma_cube',
		name: 'Strong Magma Cube',
		biome: 'volcano,cave',
		health: 2,
		attack: 3,
		attackChance: 0.9,
		defense: 3,
		defenseChance: 0.7,
		img: 'magma_cube.png',
	},
	{
		id: 'weak_ember_imp',
		name: 'Weak Ember Imp',
		biome: 'volcano,cave',
		health: 2,
		attack: 1,
		attackChance: 0.5,
		defense: 1,
		defenseChance: 0.33,
		img: 'ember_imp.png',
	},
	{
		id: 'ember_imp',
		name: 'Ember Imp',
		type: 'weapon',
		biome: 'volcano,cave',
		health: 2,
		attack: 2,
		attackChance: 0.7,
		img: 'ember_imp.png',
	},
	{
		id: 'strong_ember_imp',
		name: 'Strong Ember Imp',
		biome: 'volcano,cave',
		health: 2,
		attack: 3,
		attackChance: 0.9,
		defense: 3,
		defenseChance: 0.7,
		img: 'ember_imp.png',
	},
	{
		id: 'weak_skeleton',
		name: 'Weak Skeleton',
		biome: 'volcano,cave',
		health: 2,
		attack: 1,
		attackChance: 0.5,
		defense: 1,
		defenseChance: 0.33,
		img: 'skeleton.png',
	},
	{
		id: 'skeleton',
		name: 'Skeleton',
		biome: 'volcano,cave',
		health: 2,
		attack: 2,
		attackChance: 0.7,
		defense: 2,
		defenseChance: 0.5,
		img: 'skeleton.png',
	},
	{
		id: 'strong_skeleton',
		name: 'Strong Skeleton',
		biome: 'volcano,cave',
		health: 2,
		attack: 3,
		attackChance: 0.9,
		defense: 3,
		defenseChance: 0.7,
		img: 'skeleton.png',
	},
	{
		id: 'weak_rock_troll',
		name: 'Weak Rock Troll',
		biome: 'volcano,cave',
		health: 2,
		attack: 1,
		attackChance: 0.5,
		defense: 1,
		defenseChance: 0.33,
		img: 'rock_troll.png',
	},
	{
		id: 'rock_troll',
		name: 'Rock Troll',
		biome: 'volcano,cave',
		health: 2,
		attack: 2,
		attackChance: 0.7,
		defense: 2,
		defenseChance: 0.5,
		img: 'rock_troll.png',
	},
	{
		id: 'strong_rock_troll',
		name: 'Strong Rock Troll',
		biome: 'volcano,cave',
		health: 2,
		attack: 3,
		attackChance: 0.9,
		defense: 3,
		defenseChance: 0.7,
		img: 'rock_troll.png',
	},
	{
		id: 'weak_medusa',
		name: 'Weak Medusa',
		biome: 'volcano,cave',
		health: 2,
		attack: 1,
		attackChance: 0.5,
		defense: 1,
		defenseChance: 0.33,
		img: 'medusa.png',
	},
	{
		id: 'medusa',
		name: 'Medusa',
		biome: 'volcano,cave',
		health: 2,
		attack: 2,
		attackChance: 0.7,
		defense: 2,
		defenseChance: 0.5,
		img: 'medusa.png',
	},
	{
		id: 'strong_medusa',
		name: 'Strong Medusa',
		biome: 'volcano,cave',
		health: 2,
		attack: 3,
		attackChance: 0.9,
		defense: 3,
		defenseChance: 0.7,
		img: 'medusa.png',
	},
	{
		id: 'weak_wizard',
		name: 'Weak Wizard',
		biome: 'volcano,cave',
		health: 2,
		attack: 1,
		attackChance: 0.5,
		defense: 1,
		defenseChance: 0.33,
		img: 'wizard.png',
	},
	{
		id: 'wizard',
		name: 'Wizard',
		biome: 'volcano,cave',
		health: 2,
		attack: 2,
		attackChance: 0.7,
		defense: 2,
		defenseChance: 0.5,
		img: 'wizard.png',
	},
	{
		id: 'strong_wizard',
		name: 'Strong Wizard',
		biome: 'volcano,cave',
		health: 2,
		attack: 3,
		attackChance: 0.9,
		defense: 3,
		defenseChance: 0.7,
		img: 'wizard.png',
	},
	{
		id: 'weak_red_dragon',
		name: 'Weak Red Dragon',
		biome: 'volcano,cave',
		health: 2,
		attack: 1,
		attackChance: 0.7,
		defense: 1,
		defenseChance: 0.33,
		img: 'red_dragon.png',
	},
	{
		id: 'red_dragon',
		name: 'Red Dragon',
		biome: 'volcano,cave',
		health: 2,
		attack: 2,
		attackChance: 0.7,
		defense: 2,
		defenseChance: 0.5,
		img: 'red_dragon.png',
	},
	{
		id: 'strong_red_dragon',
		name: 'Strong Red Dragon',
		biome: 'volcano,cave',
		health: 2,
		attack: 3,
		attackChance: 0.9,
		defense: 3,
		defenseChance: 0.7,
		img: 'red_dragon.png',
	},
	{
		id: 'weak_dark_unicorn',
		name: 'Weak Dark Unicorn',
		biome: 'volcano,cave',
		health: 2,
		attack: 1,
		attackChance: 0.5,
		defense: 1,
		defenseChance: 0.33,
		img: 'dark_unicorn.png',
	},
	{
		id: 'dark_unicorn',
		name: 'Dark Unicorn',
		biome: 'volcano,cave',
		health: 2,
		attack: 2,
		attackChance: 0.7,
		defense: 2,
		defenseChance: 0.5,
		img: 'dark_unicorn.png',
	},
	{
		id: 'strong_dark_unicorn',
		name: 'Strong Dark Unicorn',
		biome: 'volcano,cave',
		health: 2,
		attack: 3,
		attackChance: 0.9,
		defense: 3,
		defenseChance: 0.7,
		img: 'dark_unicorn.png',
	},
];
